version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  neo4j:
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7688:7687"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
